### ISSUE TITLE
Dataset links not working

### ISSUE THREAD

**Issue by rohit-takhar** [mlcv-ime/faster-rcnn-graphics#1]
Hi,
I was trying to run your model but the dataset links are not valid. Can you please share correct url for flowchart dataset which you used? I tried downloading the dataset from [here ](http://ivc.univ-nantes.fr/en/databases/Flowchart/)but the data contents seem different.

Thanks,
Rohit

**Comment by youmizai** [comment]
hi
    I meet same question ,the dataset are not link . the dateset link is not download, would you give me a valid link.

**Comment by tirinox** [comment]
Same thing. Please give us valid dataset links :)

**Comment by fjulca-aguilar** [comment]
Hi,

sorry for the misleading url. You can find the datasets at:
http://www.vision.ime.usp.br/~frank.aguilar/graphics/datasets/

Also, I updated the url at the download_dataset.sh script
Enjoy it :)

**Comment by rohit-takhar** [comment]
Thanks! It is working now.
