### ISSUE TITLE
Assertion error - checkpoint_dir is missing

### ISSUE THREAD

**Issue by viral98** [mlcv-ime/faster-rcnn-graphics#2]
Upon executing the command
`python tf-models/research/object_detection/eval.py \
    --logtostderr \
    --pipeline_config_path=models/flowcharts/inceptionv2/pipeline.config \
    --checkpoint_dir=models/flowcharts/inceptionv2/trained \
    --eval_dir=models/flowcharts/inceptionv2/eval \ 
    --gpudev=0 \
    --run_once=True `
I get the following error
`File "eval.py", line 93, in main
    assert FLAGS.checkpoint_dir, '`checkpoint_dir` is missing.'
AssertionError: `checkpoint_dir` is missing.`
I followed through the setup as mentioned in the readme and everything else works perfectly fine, even executing
`python object_detection/builders/model_builder_test.py` works perfectly fine.

**Comment by 1458763783** [comment]
i face the same error, have you solve it, thanks.

**Comment by shreyanshu09** [comment]
Run each parameter in a different line like:

python tf-models/research/object_detection/eval.py \ 
--logtostderr \ 
--pipeline_config_path=models/flowcharts/inceptionv2/pipeline.config \ 
--checkpoint_dir=models/flowcharts/inceptionv2/trained \ 
--eval_dir=models/flowcharts/inceptionv2/eval \ 
--gpudev=0 \ 
--run_once=True

Hope this will help you
